
services:
  medhotel-app:
    build: .
    container_name: medhotel-app
    depends_on:
      - postgres-db
    environment:
      - DB_URL=jdbc:postgresql://postgres-db:5432/medhotel
      - DB_USER=postgres
      - DB_PASSWORD=password
    networks:
      - medhotel-network

  postgres-db:
    image: postgres:15
    container_name: medhotel-postgres
    environment:
      POSTGRES_DB: medhotel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - medhotel-network

networks:
  medhotel-network:
    driver: bridge
